###############################################################################
#
#  OPENREPEATER / SVXLINK CONFIGURATION FILE
#  This file was auto generated by OpenRepeater. 
#  DO NOT MAKE CHANGES IN THIS FILE AS THEY WILL BE OVERWRITTEN
#
###############################################################################


namespace eval Logic {
	global strdtmf;
	set strdtmf "";

	# Executed when a short identification should be sent
	proc send_short_ident {{hour -1} {minute -1}} {
	
	    global mycall;
	    variable CFG_TYPE;
	    playSilence 200;
	
	    if {$CFG_TYPE == "Repeater"} {
	
	    CW::setAmplitude 200
	    CW::setWpm 25
	    CW::setPitch 600
	    CW::play $mycall/R
	    playSilence 500;
	
	    } else {

	    CW::setAmplitude 200
	    CW::setWpm 25
	    CW::setPitch 600
	    CW::play $mycall/R
	    playSilence 500;
	
	    }

	}

	# Executed when a long identification (e.g. hourly) should be sent
	proc send_long_ident {hour minute} {
	
	    global mycall;
	    global loaded_modules;
	    global active_module;
	    variable CFG_TYPE;
	    playSilence 200;
	
	    if {$CFG_TYPE == "Repeater"} {
	
	    spellWord $mycall;
	    if {$CFG_TYPE == "Repeater"} {
	        playMsg "Core" "repeater";
	    }
	    playSilence 500;
	
	    CW::setAmplitude 200
	    CW::setWpm 25
	    CW::setPitch 600
	    CW::play $mycall/R
	    playSilence 500;
	
	    } else {

	    CW::setAmplitude 200
	    CW::setWpm 25
	    CW::setPitch 600
	    CW::play $mycall/R
	    playSilence 500;
	
	    }

	}
	
	
	#source:
	#https://sourceforge.net/p/svxlink/mailman/message/34798264/

	# Executed when a DTMF digit has been received#   digit     - The
	# detected DTMF digit duration  - The duration, in milliseconds, of
	# the digit. Return 1 to hide the digit from further processing in
	# SvxLink or return 0 to make SvxLink continue processing as
	# normal.
	#
	proc dtmf_digit_received {digit duration} {variable strdtmf;
	# puts "DTMF digit \"$digit\" detected with duration $duration ms";
	# when DTMF is coming truth a echo command, the durations are always 100ms.
	# events can by trigger by 
	# 1- launch svxlink by this command :"nc -lk 10000 | sudo svxlink"
	# 2- give interruption command via DTMF long string code with : 
	# echo 212654321### | nc 127.0.0.1 10000
	# the point 2 can by done via a network - replacing 127.0.0.1 by the distant
	# ip of svxlink
		if {$duration==100 } {
		#concatenation with global variable (declaration in namespace)
			append strdtmf  $digit;
			# value to find in the code. If find, execute a command ou playing a
			# wav sound. Reset the memory string
			if { [string first 654321# $strdtmf 0 ] != -1   } {
				spellWord "OK.";
				set strdtmf ""
			}
		}
		return 0;
	}
}
